language: node_js
node_js:
- stable
sudo: false
script: npm run $COMMAND
before_script:
- npm run lint
env:
  matrix:
  - COMMAND=test
  - COMMAND=test-browser
  - COMMAND=test-phantom
  - COMMAND=report-coverage
  global:
  - secure: I0x0qGn50XNIMSyzq3FrYvWNndWgxOxEUHu6guckOFKUdpGY+HeK6R4nPrPCixBqcSKlIYQHlCskQOWJsSmbj0cq2d/W3ooS8fqCPie24T7pvvwf3yJtylL/EpfYyR42rMYnrX4LMfYqm9Iz8WQy5yJbi/fpfsMB/ucjZDqqMueLkkFvpu/6T980ah+qA9OeVXx1XRoNCHJbSBr2hZoXpvctx4b8Tsk7WvcIs2uSG+I7xLfs/9hrnlQywLeTu47O3r05JTTvJTvbmIC6swGvyi9NkCVpwD4GeJGRQW46wlbkGzaqKknoynNQd34sbp4VDjQ2ueyaykn8gSpgktDlSBHo2wxM7PZExpuN7OiOMDOR7CCP/wlvLWQEP9+xeP37c7aWgAzQBENQ37kaiVQwnhCorEtjFVIW2Lzrmjc9DuGILG9EM+Lt23DfRGgyGt2EU/ojN50swoPd75jBOldM5PGCWE7JOAZ4LA4unzozpvCSzSVbcDNrMaa4MA311jrJzvjrCRBF+73cDxmlTIQ0gCT1V/VbI2S6tD1254L+7QaPc8pwxNxiGwXbQCHYOVV8/Z97suRqjdmWl47Cli0AmvmRtuyErbG5mX2F6r24NKMyUNjGM3ZEiNLZZ7FXWGERFokQc+gmykzjH11NTKgh6Spj6Bu4nRnT1RMG2kRE8r8=
  - secure: n5hXdgbh8Jp7ExnKc3/qFO3+IJiRxUFMosohzeXAsLmMCs6toOsXqKtZFQG8j7JYCF/8RK1XXohHriOzzsPdLJqNiNl4oonhQTHFykroQhoiG1POJgREnZqcMDJ1xdga05tatuFwzamNNIxsAJH7WjtkZtjH4/7TxWKcoA8HxLyFEskWcSyRlYeTxmCcLzG7mptpYMyKYmmuL59ICcCCb3Bxy6/bH2bN6Vw0Vui5Zhw6TUkauoYJBfqToNg+lwdw30s6+RuhNg4xaam1Cw3ert06Q3Dshug9PXY4tW0gnORtqdKWuhZcZw1vfLw3wA+z2wXqRf3tUiBEjEKSRfz+zLWmr9qn3//ps+etgPNJV/XX46Kkf1MzBLoGp76iStCL+WvldpIR1Mmhmv2DJDkK10wPw+SESHYfnsXZrIib91Pe/5vo3J9dRnKz0lRlRxhPY4andXWSqfYu9De21igL5J5hcRUu8Zbryd3WiXdK3HzOytCKJ+8+GLqhxkTMIc7qNEhr3NH1i9RBq0GHYqNsooCE757zL0wtvCdQoTchFOXTUUQIh0dQgNF2fpT/D+OHD0ER6dIWQpDxteiR4JBvJ9VeCRKG3c1VjEIAEBMvSpSfRpTrausy2e9sWSNt4bu40gXBXMqO/bIiVEf63F+aYDpkt/y3g304naEMlEElGVc=
branches:
  only:
  - master
