ui: mocha-bdd
concurrency: 4
tunnel:
  type: ngrok
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: [7, 8, 9..latest]
  - name: ie
    version: 8..latest
  - name: microsoftedge
    version: latest
  - name: iphone
    version: [7.0, 8.4, 9.2]
  - name: ipad
    version: [7.0, 8.4, 9.2]
  - name: android
    version: 4.0..latest
